server:
  port: 8089

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hospede
          uri: lb://hospede
          predicates:
            - Path=/hospedes/**
          filters:
            - name: CircuitBreaker
              args:
                name: hospede-service
                fallbackuri: forward:/hospedeServiceFallBack
        - id: reserva
          uri: lb://reserva
          predicates:
            - Path=/reservas/**
          filters:
            - name: CircuitBreaker
              args:
                name: reserva-service
                fallbackuri: forward:/reservaServiceFallBack
        - id: fraude
          uri: lb://fraude
          predicates:
            - Path=/fraude-check/**
          filters:
            - name: CircuitBreaker
              args:
                name: fraude-service
                fallbackuri: forward:/fraudeServiceFallBack

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 50

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream