server:
  port: 8080

spring:
  application:
    name: hospede
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/hospede
    password: 'root'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
          ddl-auto: update
      show-sql: 'true'