server:
  port: 8082

spring:
  application:
    name: reserva
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reserva
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest

zipkin:
  base-url: http://127.0.0.1:9411/


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus